-- Generated by Oracle SQL Developer Data Modeler 21.1.0.092.1221
--   at:        2021-06-05 15:53:24 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE additional_costs (
    additional_cost_id  NUMERIC(7) IDENTITY(1,1) NOT NULL,
    value               NUMERIC(8, 2) NOT NULL,
    cause               VARCHAR(40) NOT NULL,
    order_id			NUMERIC(32) NOT NULL
);

--COMMENT ON COLUMN additional_costs.value IS
--    '> 0';

ALTER TABLE additional_costs ADD CONSTRAINT additional_costs_pk PRIMARY KEY ( additional_cost_id );

CREATE TABLE additional_information (
    info_id      NUMERIC(3) IDENTITY(1,1) NOT NULL,
    information  VARCHAR(30) NOT NULL
);

ALTER TABLE additional_information ADD CONSTRAINT additional_information_pk PRIMARY KEY ( info_id );


--  ERROR: UK name length exceeds maximum allowed length(30) 
ALTER TABLE additional_information ADD CONSTRAINT additional_information_information_un UNIQUE ( information );

CREATE TABLE address (
    address_id            NUMERIC(5) IDENTITY(1,1) NOT NULL,
    postal_code           VARCHAR(6 ) NOT NULL,
    street_name           VARCHAR(16) NOT NULL,
    building_number       VARCHAR(5)  NOT NULL,
    apartment_number      VARCHAR(5),
    client_id      NUMERIC(5) NOT NULL,
    city_id          NUMERIC(5) NOT NULL,
    delivery_id  NUMERIC(7) NOT NULL
);

--COMMENT ON COLUMN address.postal_code IS
  --  'Weryfikacja regexem.';

--COMMENT ON COLUMN address.building_number IS
  --  'Czy jest to prawdilowy numer?';

--COMMENT ON COLUMN address.apartment_number IS
  --  'Czy jest to prawdilowy numer?';


ALTER TABLE address ADD CONSTRAINT address_pk PRIMARY KEY ( address_id );

CREATE TABLE allergen (
    allergen_id  NUMERIC(3) IDENTITY(1,1) NOT NULL,
    name         VARCHAR(20) NOT NULL
);

ALTER TABLE allergen ADD CONSTRAINT allergen_pk PRIMARY KEY ( allergen_id );

CREATE TABLE business (
    client_id  NUMERIC(5)  NOT NULL,
    nip        VARCHAR(15) NOT NULL
);

--COMMENT ON COLUMN business.nip IS
--    'Algorytm na wiki.';

ALTER TABLE business ADD CONSTRAINT business_pk PRIMARY KEY ( client_id );

ALTER TABLE business ADD CONSTRAINT business_nip_un UNIQUE ( nip );

CREATE TABLE city (
    city_id   NUMERIC(5) IDENTITY(1,1) NOT NULL,
    name      VARCHAR(20) NOT NULL,
    district  NUMERIC(20)
);

--COMMENT ON COLUMN city.name IS
--    'Zaczyna sie wielk¹ liter¹.';

ALTER TABLE city ADD CONSTRAINT city_pk PRIMARY KEY ( city_id );

CREATE TABLE client (
    client_id NUMERIC(5) IDENTITY(1,1) NOT NULL
);

ALTER TABLE client ADD CONSTRAINT client_pk PRIMARY KEY ( client_id );

CREATE TABLE delivery (
    delivery_id     NUMERIC(7) IDENTITY(1,1) NOT NULL,
    cost            NUMERIC(16, 2) NOT NULL,
    delivery_hints  VARCHAR(40),
    order_id  NUMERIC(32) NOT NULL
);

--COMMENT ON COLUMN delivery.cost IS
--    '>= 0';

ALTER TABLE delivery ADD CONSTRAINT delivery_pk PRIMARY KEY ( delivery_id );

CREATE TABLE drink_sizes (
    size_id  NUMERIC(3) IDENTITY(1,1) NOT NULL,
    size_ml  NUMERIC(5) NOT NULL
);

--COMMENT ON COLUMN drink_sizes.size_ml IS
--    '> 0';

ALTER TABLE drink_sizes ADD CONSTRAINT drink_sizes_pk PRIMARY KEY ( size_id );

CREATE TABLE drinks (
    item_id          NUMERIC(5) IDENTITY(1,1) NOT NULL,
    alcohol_content  NUMERIC(2)
);

--COMMENT ON COLUMN drinks.alcohol_content IS
--    '>= 0';

ALTER TABLE drinks ADD CONSTRAINT drinks_pk PRIMARY KEY ( item_id );

CREATE TABLE employee (
    employee_id                     NUMERIC(8) IDENTITY(1,1) NOT NULL,
    name                            VARCHAR(32) NOT NULL,
    surname                         VARCHAR(32) NOT NULL,
    pesel                           NUMERIC(32),
    phone_number                    NUMERIC(12) NOT NULL,
    bank_account_number             NUMERIC(32, 4) NOT NULL,
    order_order_id                  NUMERIC(32, 4),
    address_id						NUMERIC(5),
    delivery_id						NUMERIC(7),
    employee_type_id				NUMERIC(4) NOT NULL
);

--COMMENT ON COLUMN employee.employee_id IS
--    'aS';

--COMMENT ON COLUMN employee.name IS
  --  'Zaczyna siê wielk¹ liter¹.';

--COMMENT ON COLUMN employee.surname IS
  --  'Zaczyna siê wielk¹ liter¹.';

--COMMENT ON COLUMN employee.pesel IS
--    'Weryfikacja numeru PESEL (algorytm na wikipedii).';

--COMMENT ON COLUMN employee.phone_number IS
--    'Weryfikacja regexem.';

--COMMENT ON COLUMN employee.bank_account_number IS
--    'Weryfikacja numeru konta (na wiki).';

ALTER TABLE employee ADD CONSTRAINT employee_pk PRIMARY KEY ( employee_id );

ALTER TABLE employee ADD CONSTRAINT employee_pesel_un UNIQUE ( pesel );


--  ERROR: UK name length exceeds maximum allowed length(30) 
ALTER TABLE employee ADD CONSTRAINT employee_bank_account_number_un UNIQUE ( bank_account_number );

ALTER TABLE employee ADD CONSTRAINT employee_phone_number_un UNIQUE ( phone_number );

CREATE TABLE employee_schedule (
    employee_schedule_id  NUMERIC(7) IDENTITY(1,1) NOT NULL,
    start_date            DATE NOT NULL,
    end_date              DATE NOT NULL,
    accepted              BIT NOT NULL,
    employee_id			  NUMERIC(8)
);

--COMMENT ON COLUMN employee_schedule.start_date IS
--    'Start_date < End_date';

--COMMENT ON COLUMN employee_schedule.end_date IS
--    'Start_date < End_date';

ALTER TABLE employee_schedule ADD CONSTRAINT employee_schedule_pk PRIMARY KEY ( employee_schedule_id );

CREATE TABLE employee_type (
    employee_type_id  NUMERIC(4) IDENTITY(1,1) NOT NULL,
    type_name         VARCHAR(16) NOT NULL
);

ALTER TABLE employee_type ADD CONSTRAINT employee_type_pk PRIMARY KEY ( employee_type_id );

CREATE TABLE event_type (
    event_type_id  NUMERIC(3) IDENTITY(1,1) NOT NULL,
    event_name     VARCHAR(20) NOT NULL
);

ALTER TABLE event_type ADD CONSTRAINT event_type_pk PRIMARY KEY ( event_type_id );

ALTER TABLE event_type ADD CONSTRAINT event_type_event_name_un UNIQUE ( event_name );

CREATE TABLE item_on_the_menu (
    item_id  NUMERIC(5) IDENTITY(1,1) NOT NULL,
    name     VARCHAR(20) NOT NULL,
    cost     NUMERIC(5, 2) NOT NULL
);

--COMMENT ON COLUMN item_on_the_menu.cost IS
--    '> 0';

ALTER TABLE item_on_the_menu ADD CONSTRAINT item_on_the_menu_pk PRIMARY KEY ( item_id );

CREATE TABLE meals (
    item_id     NUMERIC(5) IDENTITY(1,1) NOT NULL,
    size_grams  NUMERIC(4) NOT NULL
);

--COMMENT ON COLUMN meals.size_grams IS
--    '> 0';

ALTER TABLE meals ADD CONSTRAINT meals_pk PRIMARY KEY ( item_id );

CREATE TABLE "Order" (
    order_id                  NUMERIC(32) IDENTITY(1,1) NOT NULL,
    start_date                DATE NOT NULL,
    end_date                  DATE NOT NULL,
    number_of_people          NUMERIC(8, 2) NOT NULL,
    base_price                NUMERIC(8, 2) NOT NULL,
    waiters_needed            BIT NOT NULL,
    client_id          NUMERIC(5) NOT NULL,
    delivery_id      NUMERIC(7) NOT NULL,
    event_type_id  NUMERIC(3) NOT NULL
);

--COMMENT ON COLUMN "Order".start_date IS
--    'Start_date < End_date';

--COMMENT ON COLUMN "Order".end_date IS
--    'Start_date < End_date';

--COMMENT ON COLUMN "Order".number_of_people IS
--    '> 0 && < 400';

--COMMENT ON COLUMN "Order".base_price IS
 --   '> 0';


ALTER TABLE "Order" ADD CONSTRAINT order_pk PRIMARY KEY ( order_id );

CREATE TABLE ordered_meals (
    ordered_meal_id           NUMERIC(7) IDENTITY(1,1) NOT NULL,
    number_of_ordered_meals   NUMERIC(8) NOT NULL,
    additional_instructions   VARCHAR(32),
    order_id            NUMERIC(32, 4) NOT NULL,
    item_id  NUMERIC(5) NOT NULL
);

--COMMENT ON COLUMN ordered_meals.number_of_ordered_meals IS
--    '> 0';

ALTER TABLE ordered_meals ADD CONSTRAINT ordered_meals_pk PRIMARY KEY ( ordered_meal_id );

CREATE TABLE person (
    client_id     NUMERIC(5)  NOT NULL,
    name          VARCHAR(25) NOT NULL,
    surname       VARCHAR(25) NOT NULL,
    phone_number  VARCHAR(15) NOT NULL,
    email         VARCHAR(40)
);

--COMMENT ON COLUMN person.name IS
--    'Czy zaczyna siê wielk¹ liter¹?';

--COMMENT ON COLUMN person.surname IS
--    'Czy zaczyna siê wielk¹ liter¹?';

--COMMENT ON COLUMN person.phone_number IS
--    'Weryfikacja regexem';

--COMMENT ON COLUMN person.email IS
--    'Weryfikacja regexem';

ALTER TABLE person ADD CONSTRAINT person_pk PRIMARY KEY ( client_id );

CREATE TABLE product (
    catalog_number                VARCHAR(20) NOT NULL,
    name                          VARCHAR(32) NOT NULL,
    wholesale_price               NUMERIC(5, 2) NOT NULL,
    batch_number  VARCHAR(15)
);

--COMMENT ON COLUMN product.wholesale_price IS
 --   '> 0';

ALTER TABLE product ADD CONSTRAINT product_pk PRIMARY KEY ( catalog_number );

CREATE TABLE info_about_item (
    info_id  NUMERIC(3) NOT NULL,
    item_id  NUMERIC(5) NOT NULL
);

ALTER TABLE info_about_item ADD CONSTRAINT info_about_itempk PRIMARY KEY ( info_id,
                                                                    item_id );

CREATE TABLE ingredients (
    item_id  NUMERIC(5) NOT NULL,
    product_catalog_number    VARCHAR(20) NOT NULL
);

ALTER TABLE ingredients ADD CONSTRAINT ingredients_pk PRIMARY KEY ( item_on_the_menu_item_id,
                                                                    product_catalog_number );

CREATE TABLE allergens_in_product (
    allergen_id    NUMERIC(3) NOT NULL,
    product_catalog_number  VARCHAR(20) NOT NULL
);

ALTER TABLE relation_14 ADD CONSTRAINT relation_14_pk PRIMARY KEY ( allergen_allergen_id,
                                                                    product_catalog_number );

CREATE TABLE relation_31 (
    drink_sizes_id  NUMERIC(3) NOT NULL,
    drinks_item_id       NUMERIC(5) NOT NULL
);

ALTER TABLE relation_31 ADD CONSTRAINT relation_31_pk PRIMARY KEY ( drink_sizes_size_id,
                                                                    drinks_item_id );

CREATE TABLE relation_8 (
    delivery_id  NUMERIC(7) NOT NULL,
    vehicle_id   NUMERIC(8, 4) NOT NULL
);

ALTER TABLE relation_8 ADD CONSTRAINT relation_8_pk PRIMARY KEY ( delivery_delivery_id,
                                                                  vehicles_vehicle_id );

CREATE TABLE storage (
    storage_id                    NUMERIC(2) NOT NULL,
    name                          VARCHAR(20) NOT NULL,
    stored_products_batch_number  VARCHAR(15)
);

ALTER TABLE storage ADD CONSTRAINT storage_pk PRIMARY KEY ( storage_id );

ALTER TABLE storage ADD CONSTRAINT storage_name_un UNIQUE ( name );

CREATE TABLE stored_products (
    batch_number      VARCHAR(15) NOT NULL,
    available_amount  NUMERIC(10, 2) NOT NULL,
    expiration_date   DATE NOT NULL
);

--COMMENT ON COLUMN stored_products.batch_number IS
--    'Weryfikacja regexem.';

--COMMENT ON COLUMN stored_products.available_amount IS
 --   '> 0';

ALTER TABLE stored_products ADD CONSTRAINT stored_products_pk PRIMARY KEY ( batch_number );

CREATE TABLE vehicles (
    vehicle_id  NUMERIC(8) IDENTITY(1,1) NOT NULL,
    capacity    NUMERIC(32, 4) NOT NULL,
    fuel_usage  NUMERIC(8, 4) NOT NULL
);

--COMMENT ON COLUMN vehicles.capacity IS
--    '> 0';

--COMMENT ON COLUMN vehicles.fuel_usage IS
--    '> 0';

ALTER TABLE vehicles ADD CONSTRAINT vehicles_pk PRIMARY KEY ( vehicle_id );

ALTER TABLE additional_costs
    ADD CONSTRAINT additional_costs_order_fk FOREIGN KEY ( order_order_id )
        REFERENCES "Order" ( order_id );

ALTER TABLE address
    ADD CONSTRAINT address_city_fk FOREIGN KEY ( city_city_id )
        REFERENCES city ( city_id );

ALTER TABLE address
    ADD CONSTRAINT address_client_fk FOREIGN KEY ( client_client_id )
        REFERENCES client ( client_id );

ALTER TABLE address
    ADD CONSTRAINT address_delivery_fk FOREIGN KEY ( delivery_delivery_id )
        REFERENCES delivery ( delivery_id );

ALTER TABLE business
    ADD CONSTRAINT business_client_fk FOREIGN KEY ( client_id )
        REFERENCES client ( client_id );

ALTER TABLE delivery
    ADD CONSTRAINT delivery_order_fk FOREIGN KEY ( order_order_id )
        REFERENCES "Order" ( order_id );

ALTER TABLE drinks
    ADD CONSTRAINT drinks_item_on_the_menu_fk FOREIGN KEY ( item_id )
        REFERENCES item_on_the_menu ( item_id );

ALTER TABLE employee
    ADD CONSTRAINT employee_address_fk FOREIGN KEY ( address_id )
        REFERENCES address ( address_id );

ALTER TABLE employee
    ADD CONSTRAINT employee_delivery_fk FOREIGN KEY ( delivery_id )
        REFERENCES delivery ( delivery_id );

ALTER TABLE employee
    ADD CONSTRAINT employee_employee_type_fk FOREIGN KEY ( employee_type_employee_type_id )
        REFERENCES employee_type ( employee_type_id );

ALTER TABLE employee
    ADD CONSTRAINT employee_order_fk FOREIGN KEY ( order_order_id )
        REFERENCES "Order" ( order_id );

ALTER TABLE employee_schedule
    ADD CONSTRAINT employee_schedule_employee_fk FOREIGN KEY ( employee_employee_id )
        REFERENCES employee ( employee_id );

ALTER TABLE meals
    ADD CONSTRAINT meals_item_on_the_menu_fk FOREIGN KEY ( item_id )
        REFERENCES item_on_the_menu ( item_id );

ALTER TABLE "Order"
    ADD CONSTRAINT order_client_fk FOREIGN KEY ( client_client_id )
        REFERENCES client ( client_id );

ALTER TABLE "Order"
    ADD CONSTRAINT order_delivery_fk FOREIGN KEY ( delivery_delivery_id )
        REFERENCES delivery ( delivery_id );

ALTER TABLE "Order"
    ADD CONSTRAINT order_event_type_fk FOREIGN KEY ( event_type_event_type_id )
        REFERENCES event_type ( event_type_id );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE ordered_meals
    ADD CONSTRAINT ordered_meals_item_on_the_menu_fk FOREIGN KEY ( item_on_the_menu_item_id )
        REFERENCES item_on_the_menu ( item_id );

ALTER TABLE ordered_meals
    ADD CONSTRAINT ordered_meals_order_fk FOREIGN KEY ( order_order_id )
        REFERENCES "Order" ( order_id );

ALTER TABLE person
    ADD CONSTRAINT person_client_fk FOREIGN KEY ( client_id )
        REFERENCES client ( client_id );

ALTER TABLE product
    ADD CONSTRAINT product_stored_products_fk FOREIGN KEY ( stored_products_batch_number )
        REFERENCES stored_products ( batch_number );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE info_about_item
    ADD CONSTRAINT info_about_item_additional_information_fk FOREIGN KEY ( additional_information_info_id )
        REFERENCES additional_information ( info_id );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE info_about_item
    ADD CONSTRAINT info_about_item_item_on_the_menu_fk FOREIGN KEY ( item_on_the_menu_item_id )
        REFERENCES item_on_the_menu ( item_id );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE ingredients
    ADD CONSTRAINT ingredients_item_on_the_menu_fk FOREIGN KEY ( item_on_the_menu_item_id )
        REFERENCES item_on_the_menu ( item_id );

ALTER TABLE ingredients
    ADD CONSTRAINT ingredients_product_fk FOREIGN KEY ( product_catalog_number )
        REFERENCES product ( catalog_number );

ALTER TABLE relation_14
    ADD CONSTRAINT relation_14_allergen_fk FOREIGN KEY ( allergen_allergen_id )
        REFERENCES allergen ( allergen_id );

ALTER TABLE relation_14
    ADD CONSTRAINT relation_14_product_fk FOREIGN KEY ( product_catalog_number )
        REFERENCES product ( catalog_number );

ALTER TABLE relation_31
    ADD CONSTRAINT relation_31_drink_sizes_fk FOREIGN KEY ( drink_sizes_size_id )
        REFERENCES drink_sizes ( size_id );

ALTER TABLE relation_31
    ADD CONSTRAINT relation_31_drinks_fk FOREIGN KEY ( drinks_item_id )
        REFERENCES drinks ( item_id );

ALTER TABLE relation_8
    ADD CONSTRAINT relation_8_delivery_fk FOREIGN KEY ( delivery_delivery_id )
        REFERENCES delivery ( delivery_id );

ALTER TABLE relation_8
    ADD CONSTRAINT relation_8_vehicles_fk FOREIGN KEY ( vehicles_vehicle_id )
        REFERENCES vehicles ( vehicle_id );

ALTER TABLE storage
    ADD CONSTRAINT storage_stored_products_fk FOREIGN KEY ( stored_products_batch_number )
        REFERENCES stored_products ( batch_number );

--  ERROR: No Discriminator Column found in Arc FKArc_3 - constraint trigger for Arc cannot be generated 

--  ERROR: No Discriminator Column found in Arc FKArc_3 - constraint trigger for Arc cannot be generated

--  ERROR: No Discriminator Column found in Arc FKArc_4 - constraint trigger for Arc cannot be generated 

--  ERROR: No Discriminator Column found in Arc FKArc_4 - constraint trigger for Arc cannot be generated



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            28
-- CREATE INDEX                             4
-- ALTER TABLE                             66
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                  11
-- WARNINGS                                 0
