name: verify-app

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    name: Check app on Linux (Ubuntu)
        
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        sudo apt-get install python-pip
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        python -m pip install pyodbc
        sudo apt-get install python3-tk
    
    - name: Lint with flake8
      run: |
        flake8 ${{github.workspace}}/app/src --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 ${{github.workspace}}/app/src --count --exit-zero --max-complexity=10 --max-line-length=130 --statistics
        
    - name: Test with pytest
      run: |
        pytest ${{github.workspace}}/app/tests

  windows:
    runs-on: windows-latest
    name: Check app on Windows

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        python -m pip install pyodbc

    - name: Lint with flake8
      run: |
        flake8 ${{github.workspace}}/app/src --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 ${{github.workspace}}/app/src --count --exit-zero --max-complexity=10 --max-line-length=130 --statistics
        
    - name: Test with pytest
      run: |
        pytest ${{github.workspace}}/app/tests
